version: "3.8"

services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: always
    ports:
      - "8090:5000" # Host:8090 -> Container:5000
    volumes:
      - ./data:/kavita/config
      - ./media:/media
      - ./logs:/kavita/logs
    environment:
      - TZ=Europe/Skopje
      - UID=1000
      - GID=1000
    networks:
      - kavita-net

networks:
  kavita-net:
    driver: bridge

