services:
  db:
    image: postgres:16
    container_name: nextcloud-postgres
    restart: always
    mem_limit: 2g
    memswap_limit: 2g
    cpus: '1.0'
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: change_me_strong
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app:
    image: nextcloud:30-apache
    container_name: nextcloud-app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: change_me_strong
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.gmojsoski.com
      NEXTCLOUD_OVERWRITEHOST: cloud.gmojsoski.com
      NEXTCLOUD_OVERWRITEPROTOCOL: https
    volumes:
      - ./app:/var/www/html
    ports:
      - "8081:80"
    mem_limit: 4g
    memswap_limit: 4g
    cpus: '1.0'
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
